### ISSUE TITLE
MODULE_NOT_FOUND: model-catalog.cjs uses brittle relative path that breaks after install (regression from #3230)

### ISSUE THREAD

**Issue by j2h4u** [gsd-build/get-shit-done#3288]
## Summary
After install, `get-shit-done/bin/lib/model-catalog.cjs` fails with `MODULE_NOT_FOUND` because it `require()`s `model-catalog.json` via a relative path that only resolves correctly in the source repo, not in the installed `~/.claude/` layout.

This breaks **every CJS tool that depends on `core.cjs`** — `gsd-tools.cjs`, almost any `node ~/.claude/get-shit-done/bin/gsd-tools.cjs <command>` invocation, and indirectly the `gsd-sdk` fallback bridge ("`config` not in native registry; falling back to gsd-tools.cjs").

Regression introduced by PR #3230 / commit `7a1e4081` (issue #3229).

## Reproduction

After a fresh global install on Claude runtime:

```bash
$ node ~/.claude/get-shit-done/bin/gsd-tools.cjs --help
Error: Cannot find module '/home/<user>/.claude/sdk/shared/model-catalog.json'
Require stack:
- ~/.claude/get-shit-done/bin/lib/model-catalog.cjs
- ~/.claude/get-shit-done/bin/lib/model-profiles.cjs
- ~/.claude/get-shit-done/bin/lib/core.cjs
- ~/.claude/get-shit-done/bin/gsd-tools.cjs
```

## Root cause

`get-shit-done/bin/lib/model-catalog.cjs:4`:

```js
const catalog = require(path.join(__dirname, '..', '..', '..', 'sdk', 'shared', 'model-catalog.json'));
```

This climbs three levels up from `bin/lib/`:

| Context | `__dirname` | Resolved path |
|---|---|---|
| Source repo | `<repo>/get-shit-done/bin/lib/` | `<repo>/sdk/shared/model-catalog.json` ✅ |
| After install | `~/.claude/get-shit-done/bin/lib/` | `~/.claude/sdk/shared/model-catalog.json` ❌ |

The installer copies `get-shit-done/` into `~/.claude/get-shit-done/` but does **not** propagate `sdk/shared/` to a sibling location. The `import.meta.url`-based path in `sdk/src/model-catalog.ts` works fine (Node follows the `~/.local/bin/gsd-sdk` symlink to the repo's `dist/cli.js`), but the **CJS copy** has no such redirection.

## Suggested fixes (any one)

1. **Install-side**: extend the install manifest to copy `sdk/shared/model-catalog.json` to `~/.claude/sdk/shared/` (or to a path the CJS module is rewritten to expect).
2. **CJS-side**: in `model-catalog.cjs`, replace the brittle three-level relative path with a resolve chain that also tries:
   - `path.resolve(__dirname, '../../sdk/shared/model-catalog.json')` (one level up — covers a future install layout that ships the catalog with the get-shit-done payload)
   - `process.env.GSD_SDK_DIR` if set
   - The location returned by resolving the `gsd-sdk` shim (`require('child_process').execSync('command -v gsd-sdk')` → readlink → `../shared/...`)

Option 1 is the smallest change; option 2 is more robust against future layout changes.

## Local workaround

```bash
ln -s <repo>/sdk ~/.claude/sdk
```

## Environment
- Version: `1.50.0-canary.0`
- Runtime: Claude (also affects Codex/OpenCode global installs in our deploy fork)
- OS: Debian 13 (trixie)
- Install path: global (`node bin/install.js --claude --codex --opencode --global --no-sdk`)

**Comment by j2h4u** [comment]
Cross-ref: #3234 (open, in-progress) addresses the broader install-layout-probing brittleness on the SDK query side via a compatibility adapter. The same architectural direction would naturally cover this CJS `model-catalog.cjs` case too — moving the catalog read behind a layout-aware resolver would eliminate the regression introduced here. Filing this separately because the regression is concrete, currently breaks every CJS tool transitively dependent on `core.cjs`, and likely warrants a smaller targeted fix that can land before #3234 completes.

**Comment by j2h4u** [comment]
Fixed by PR #3293 (landed in upstream main). Verified locally: installer now outputs `✓ Installed get-shit-done/bin/shared/model-catalog.json` and `model-catalog.cjs` resolves via the co-located path before the legacy `sdk/shared/` fallback. Local workaround (`~/.claude/sdk` symlink in `gsd-update.sh`) removed after confirming `gsd-tools.cjs` works without it.
